# Generated by Django 3.1.4 on 2020-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatlog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabAlteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('alterations', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='chatbot',
            name='vocab_list',
            field=models.TextField(null=True),
        ),
    ]
