# Generated by Django 3.1.4 on 2020-12-14 22:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201212_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='text_content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
