# Generated by Django 3.1.4 on 2020-12-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201214_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabalteration',
            name='bot_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.chatbot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='text_content',
            field=models.TextField(null=True),
        ),
    ]
