# Generated by Django 3.1.4 on 2020-12-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201219_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='vocab_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='text_content',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
