# Generated by Django 3.1.4 on 2020-12-21 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20201220_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='icon_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='icon_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vocabalteration',
            name='alterations',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('stories', models.JSONField(null=True)),
                ('vocabs', models.JSONField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
