# Generated by Django 3.1.4 on 2020-12-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201222_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='bot_name',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='path',
            field=models.CharField(default='Dude', max_length=20),
            preserve_default=False,
        ),
    ]
