# Generated by Django 3.1.4 on 2021-03-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201228_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='text_content',
        ),
    ]
