# Generated by Django 3.1.4 on 2021-03-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_chatlog_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='vocab_list',
        ),
    ]
