# Generated by Django 3.1.4 on 2021-03-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_chatbot_vocab_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='text_content',
            field=models.JSONField(null=True),
        ),
    ]
