# Generated by Django 3.1.4 on 2021-04-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_chatbot_public_vocab'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='nr_stories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
