# Generated by Django 3.1.4 on 2021-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userprofileinfo_nr_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabalteration',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='nr_vocabs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabalteration',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
