# Generated by Django 3.1.4 on 2021-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210424_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabalteration',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
