
MAX_INPUT_SENTENCE_LENGTH = 500
MAX_NR_PARAGRAPHS = 40
MAX_NR_CHAPTERS = 40
NR_CONTENT_META_DATA = 3
MAX_NR_CONTENT_ITEMS = MAX_NR_PARAGRAPHS + MAX_NR_CHAPTERS + NR_CONTENT_META_DATA
MAX_OUTPUT_SENTENCE_LENGTH = 40
MAX_PARAGRAPH_LENGTH = 5000
PARAGRAPH_LENGTH_LEYWAY = 200  # In case AI writes an extra sentence to pragraph
CHAPTER_MAX_LENGTH = 200
MAX_TITLE_LENGTH = 200
MAX_CHATLOG_LENGTH = 100000
MAX_VOCAB_LENGTH = 100
MAX_VOCAB_CONTENT_LENGTH = MAX_VOCAB_LENGTH + 3 # includes token and chatbot in request
MAX_WORD_SIZE = 20
MAX_STORIES_PER_USER = 20
MAX_VOCABS_PER_USER = 20

CHATBOT_MODEL_FILES = {
    'movie_dialog': 'movie_dialog_dlm.pickle',
    'lord_of_ring': 'lord_of_ring_dlm.pickle',
}
